### ISSUE TITLE
validation error throws js exception while using with IE 9 and jquery 1.9

### ISSUE THREAD

**Issue by safr0** [erichexter/twitter.bootstrap.mvc#67] opened 2013-02-03 13:21 UTC
any idea about that? Also what if I don't want to have validation errors in the alerts box but next to my client controls. plz do help i'm very new to js programming

**Comment by serra** [comment] 2013-02-03 15:52
Could this be related to #60? That jQuery 1.9 err is now fixed in code, but not yet shipped to  NuGet afaik.

**Comment by safr0** [comment] 2013-02-03 15:59
the issue you mentioned is not related to validation rather i faced that problem while setting up this nuget package so i used jquery.migrate and got rid of .map file after reading on some forums and that was pretty much about it. 

This error comes into the play e.g. submitting a login form with wrong credentials... and validation msgs from server are to be displayed on the IE client.

**Comment by serra** [comment] 2013-02-04 07:14
OK. Can you tell us how to reproduce this error using `twitter.bootstrap.mvc4.sample` - you can pull the package either from [nuget](https://www.nuget.org/packages/twitter.bootstrap.mvc4.sample/), or (better) [check out the source](https://github.com/erichexter/twitter.bootstrap.mvc#contribute) and send a pull request.

**Comment by safr0** [comment] 2013-02-04 08:57
Right now I can't do that because i've so many other scripts within my
solutions it can be literally anything. earlier i was looking into it and I
found jquery1.9 validation issue with IE on the jquery forum... it wasn't
the same issue but jquery1.9 seems to have validation issues with IE9 which
I'm not quite sure of right now. i'll have to get rid of this issue soon so
i'll definitely look into and will update you

Regards,
Muhammad Amir
Voice: +853 63244425

On Mon, Feb 4, 2013 at 3:14 PM, Marijn van der Zee <notifications@github.com

**Comment by serra** [comment] 2013-02-04 10:13
OK, let us know if it turns out to be an issue in this project.

**Comment by safr0** [comment] 2013-02-04 10:16
just for reference this is what i was talking about bit earlier

http://forum.jquery.com/topic/mvc-jquery-validation-not-clear-after-jquery-1-9

Regards,
Muhammad Amir
Voice: +853 63244425

On Mon, Feb 4, 2013 at 3:13 PM, Marijn van der Zee <notifications@github.com

**Closed as completed** 2014-11-13 04:53 UTC
