### ISSUE TITLE
Error when trying to NUGET install

### ISSUE THREAD

**Issue by MilesHart** [erichexter/twitter.bootstrap.mvc#100] opened 2014-05-22 17:02 UTC
Updating 'jQuery 1.9.1' to 'jQuery 1.4.1' failed. Unable to find versions of 'bootstrap, jQuery.Migrate, Microsoft.jQuery.Unobtrusive.Ajax, Microsoft.jQuery.Unobtrusive.Validation' that are compatible with 'jQuery 1.4.1'.

I didn't know I had to manually do this? isn't this automated in Nuget?

**Comment by kmiloaguilar** [comment] 2014-11-12 21:05
I had the same error. Any possible fix? @erichexter ?

**Comment by erichexter** [comment] 2014-11-12 22:05
Since the release of mvc5, I stopped maintaining this package. Seemed like
a lost cause. What version of mvc are you trying to use this on?

The dependencies ended up breaking between jquery, because I did not lock
down the specific versions this package depended on. If we can determine
the exact versions, I can update the nuspec file. The problem is in order
to make this work, you would get a bunch of old versions of jquery, ect. so
the first thing you will want to do is upgrade them which may or may not
work.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by kmiloaguilar** [comment] 2014-11-12 22:23
https://github.com/erichexter/twitter.bootstrap.mvc/pull/101 I removed the dependencies of version number for bootstrap and asp.net optimization.

I'm using MVC5

**Comment by kmiloaguilar** [comment] 2014-11-12 22:37
@erichexter can you help me a way how to test the nuget locally?

**Comment by kmiloaguilar** [comment] 2014-11-12 22:54
I was able to test it locally, will submit another pull request soon with the fix.

**Comment by kmiloaguilar** [comment] 2014-11-12 23:13
@erichexter I just fix this and tested locally. Here is the pull request: https://github.com/erichexter/twitter.bootstrap.mvc/pull/102, also I found a lot of other errors when installed locally. I will work on this. Can you check it?

**Comment by erichexter** [comment] 2014-11-12 23:29
I will check it tonight. What version of vs and mvc are you trying this on?

On Wednesday, November 12, 2014, Camilo Aguilar notifications@github.com
wrote:

> @erichexter https://github.com/erichexter I just fix this and tested
> locally. Here is the pull request: #102
> https://github.com/erichexter/twitter.bootstrap.mvc/pull/102, also I
> found a lot of other errors when installed locally. I will work on this.
> Can you check it?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/erichexter/twitter.bootstrap.mvc/issues/100#issuecomment-62813111
> .

## 

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by kmiloaguilar** [comment] 2014-11-12 23:37
Visual Studio 2013 and MVC5.

**Comment by kmiloaguilar** [comment] 2014-11-13 03:18
@erichexter you can close this one.

**Closed as completed** 2014-11-13 04:03 UTC
