### ISSUE TITLE
Twitter Bootstrap for ASP.Net MVC 4 Sample 1.1.100 Crash

### ISSUE THREAD

**Issue by ahmed-sherien** [erichexter/twitter.bootstrap.mvc#99] opened 2013-10-10 22:29 UTC
I just installed Twitter Bootstrap for ASP.Net MVC 4 Sample 1.1.100, it gave the following error:
- Error 1   The name 'NavigationRouteFilters' does not exist in the current context
- Error 2   'System.Web.Routing.RouteValueDictionary' does not contain a definition for 'HasFilterToken' and no extension method 'HasFilterToken' accepting a first argument of type 'System.Web.Routing.RouteValueDictionary' could be found (are you missing a using directive or an assembly reference?)
- Error 3   'System.Web.Routing.RouteValueDictionary' does not contain a definition for 'FilterToken' and no extension method 'FilterToken' accepting a first argument of type 'System.Web.Routing.RouteValueDictionary' could be found (are you missing a using directive or an assembly reference?)
- Error 4   The type or namespace name 'NavigationRouteOptions' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ahmed-sherien** [comment] 2013-10-10 22:39
I think you didn't upload navigationroutes.mvc4 -Version 1.1.100

**Comment by erichexter** [comment] 2013-10-11 01:01
that version does not exist

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by ahmed-sherien** [comment] 2013-10-11 06:16
When I uninstalled the 1.1.100 versions and installed the 1.0.90 ones things went well no errors anywhere ...

**Comment by serra** [comment] 2013-10-11 08:04
I can confirm that installing package version 1.1.100 into an empty MVC4 application does NOT give the user a compiling project.

IMO this is another loose end of navigation routes "overhaul". Related #68 #82.

**Comment by ScottL7** [comment] 2013-10-13 01:43
I too am having the exact same build errors along with 3 additional errors:
I started with an empty MVC4 project, added the sample via NuGet tried to build and generated the errors below:
![2013-10-12_21-34-53](https://f.cloud.github.com/assets/5673988/1321269/be09cda0-33a7-11e3-8b8a-3ade5453a184.png)

**Comment by leemccolm** [comment] 2013-10-14 18:42
I am also having this problem.

**Comment by allen-of-yore** [comment] 2013-10-14 18:48
Me too. Since Friday. Now Monday 10/14. Exact same issues.

**Comment by jgajeway** [comment] 2013-10-14 19:46
Is there ANY solution to this?  Pretty much the same for me, created an Empty MVC 4 project, added bootstrap nuget package, added sample nuget package, solution will not build.  Tried a few workarounds but nothing worked and it looks like even trying to specify an earlier version of the bootstap nuget package still installs 1.1.1

**Comment by jgajeway** [comment] 2013-10-14 19:53
I guess if you don't want to take advantage of the routing that's set up for you you can just comment out the code.  It's not the most ideal solution but it worked for me since I really don't need that for this simple project.  Would be nice to have a working sample though.

**Comment by allen-of-yore** [comment] 2013-10-17 19:22
Hello - It's been a few days now - like a week. Has anyone encountered a fix for this? Does anyone know if ANYONE is working on a fix? Thanks.

**Comment by erichexter** [comment] 2013-10-17 19:45
I have not had any spare cycles to look I to this. With the release of vs
2013, they support bootstrap out if the box I am not sure there is much
need for this project going forward

On Thursday, October 17, 2013, Allen wrote:

> Hello - It's been a few days now - like a week. Has anyone encountered a
> fix for this? Does anyone know if ANYONE is working on a fix? Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/erichexter/twitter.bootstrap.mvc/issues/99#issuecomment-26540629
> .

## 

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by ScottL7** [comment] 2013-10-17 19:56
Hi Eric, interestingly the currently release version of VS 2013 RC uses Bootstrap v2.3, but the latest bootstrap version is v3.0.  I found a good website that provides step-by-step procedures on how to update 2013's Bootstrap: 
Using Bootstrap 3 with Visual Studio 2013 ASP.NET MVC Template by Ghislain Proulx: http://www.ghislainproulx.net/Blog/2013/09/using-bootstrap-3-with-visual-studio-2013-aspnet-mvc-template

**Comment by erichexter** [comment] 2013-10-17 20:25
I believe the soon to be released version will have 3.0

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by ScottL7** [comment] 2013-10-17 20:33
Either way, thank you for all you have done!!! It is tremendously appreciated!!!

Warmest regards,
 = Scott =

**Comment by allen-of-yore** [comment] 2013-10-17 20:35
Eric:  Thanks for the reply.
I wasn't aware that vs2013 was out of beta.
Thanks much.

Allen

**Comment by erichexter** [comment] 2013-10-17 20:37
vs2013 was released on msdn today.. go get it and try it out

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by allen-of-yore** [comment] 2013-10-17 20:40
Will do and Thanks much!

Allen Simmer

**Comment by erichexter** [comment] 2013-10-18 00:35
I will get this version patched but it will not be upgraded now that the
asp.net team will maintain this for mvc5. I will extract the runtime
scaffolding and make that work with the new mvc 5 templates.

The only outstanding issue is if the community thinks the navigation is
valuable, if there is the need for it we could just extract that and make
it work with the new packages

On Thursday, October 17, 2013, Allen wrote:

> Will do and Thanks much!
> 
> Allen Simmer
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/erichexter/twitter.bootstrap.mvc/issues/99#issuecomment-26550785
> .

## 

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by serra** [comment] 2013-10-18 07:09
:+1: this is the way to go

**Comment by ayagoub** [comment] 2013-10-22 19:51
Hi,

I tried VS2013 with bootstrap 3, i think there is a problem with HTML helpers (@Html.EditorFor() use Bootsrap 2 input classes).

And with mvc 4 i am blocked with HasFilterToken() and FilterToken().

Any idea please.

**Comment by elhaix** [comment] 2013-10-28 17:11
Same issue as listed here: http://stackoverflow.com/questions/19618771/how-to-resolve-mvc4-twitter-bootstrap-project-fail-from-simple-nuget-installatio/19638918?noredirect=1#19638918 - and those files were dated October 26, 2013.  What's the solution?

**Comment by ryandh** [comment] 2013-10-29 00:51
yes, I got the same errors. on the vs2012 
![image](https://f.cloud.github.com/assets/5561911/1425284/4134bdc8-4034-11e3-98e1-2da092af552b.png)

![image](https://f.cloud.github.com/assets/5561911/1425285/47bf6332-4034-11e3-81a2-91c295ead894.png)

``` xml
nuget dependencies
  <package id="Twitter.Bootstrap" version="2.3.2" targetFramework="net45" />
  <package id="twitter.bootstrap.mvc4" version="1.1.100" targetFramework="net45" />
  <package id="twitter.bootstrap.mvc4.htmlhelpers" version="1.1.100" targetFramework="net45" />
  <package id="twitter.bootstrap.mvc4.sample" version="1.1.100" targetFramework="net45" />
  <package id="WebApiTestClient" version="1.1.1" targetFramework="net45" />
```

**Comment by SRIRAM0905** [comment] 2013-11-19 18:04
Hi Eric:Please help me out,is that doable

I am having the same problem,mine is  little bit complex.

1)I installed MVC 4.0 template on vs 2010 with 4.0 FRAME WORK.
2)Then i installed Bootstrap ,and examples for MVC 4.0  same error.........................

i  am unable to fix this problem........ 

![untitled](https://f.cloud.github.com/assets/5521603/1574865/e658cc42-5144-11e3-931b-fd8647bab8c9.JPG)
 in VS 2010 using 4.0 framework on MVC 4.0 template

**Comment by titombo** [comment] 2013-12-05 12:51
Same problem as above

**Comment by bking1579** [comment] 2014-01-01 21:41
Some of us are small shops and don't always jump on the latest version of Visual Studio. Anyone have a simple, repeatable fix for this without upgrading to VS2013?

**Comment by ColdFireDesigns** [comment] 2014-01-30 19:34
Same! I have this issue, and it's still not resolved.

**Comment by jgajeway** [comment] 2014-01-30 20:15
its not going to be resolved most likely, with the bootstrap template coming out for MVC5 (or already out I guess I should say) there is no need for this.  So I'm guessing someone will just have to fix it on their own and post the fix or you will just have to find a new solution if you can't upgrade visual studio to the latest and greatest

**Comment by veve90** [comment] 2014-03-19 17:06
I have the same problem! Is smb having a solution for this?

**Comment by serra** [comment] 2014-03-20 07:25
As a workaround, try installing version 1.0.90. There is  [a how-to on SO](http://stackoverflow.com/a/19638918/322283). This issue is unlikely to be resolved.

Version 1.0.90 will give you most of the stuff you need.

**Comment by bardware** [comment] 2014-06-12 20:44
It's not about integrating bootstrap with an ASP.NET project but about having a working sample to look at when developing.

**Comment by kmiloaguilar** [comment] 2014-11-13 13:58
@erichexter you need to update the navigation routes nuget package. I submitted a few hours a pull request that will fix this also, but you need to update from the latest you have in that other repo NavigationRoutes

**Comment by erichexter** [comment] 2014-11-13 14:25
done

**Comment by kmiloaguilar** [comment] 2014-11-13 14:32
Is that updated in nuget? Can you remind my your nuget feed?

**Comment by erichexter** [comment] 2014-11-13 14:46
http://www.myget.org/F/erichexter/

its listed under Preview Releases in the Readme.md

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by kmiloaguilar** [comment] 2014-11-20 17:13
I confirm that this is fixed. @erichexter

**Closed as completed** 2014-11-20 21:59 UTC
